version: '3.9'
services:
    db:
      container_name: postgres
      image: postgres:14.1
      environment:
        POSTGRES_DB: product_shop
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 12345678
      restart: always
      ports:
        - 5432:5432
      volumes:
        - ./_data/pg_data:/var/lib/postgresql/data
    redis:
      container_name: redis
      image: redis:6.2.6-alpine
      environment:
      - ALLOW_EMPTY_PASSWORD=yes
      ports:
      - 6379:6379
      volumes:
       - ./_data/redis:/data
       - ./config/redis_cfg/redis.conf:/redis.conf
      command: redis-server /redis.conf
    webapi:
      container_name: webapi
      image: sing3demons/go-api-v2-product:0.0.9
      # build: .
      ports:
        - 8080:8080
      restart: always
      environment:
        - PORT=8080
        - DB_USER=postgres
        - DB_NAME=product_shop
        - DB_PASSWORD=12345678
        - DB_PORT=5432
        - DB_HOST=db
        - SECRET_KEY=711E9CB1-3059-44FC-B8F7-59D8DE148CF1
        - APP_ENV=deverlopment
        - GIN_MODE=debug
        - REDIS_HOST=redis
        - REDIS_PORT=6379
      volumes:
        - "./uploads:/uploads"
      depends_on:
        - db
        - redis
      links:
        - "db:db"
